#ifndef LIPILEKHIKA_TYPING_H
#define LIPILEKHIKA_TYPING_H

#pragma once

/* Autogenerated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Status codes returned by the C ABI.
 */
typedef enum LipiStatus {
  Ok = 0,
  NullPtr = 1,
  InvalidUtf8 = 2,
  Panic = 3,
  Error = 4,
} LipiStatus;

/**
 * Opaque handle type used by the C ABI.
 *
 * Intentionally **not** `#[repr(C)]` so cbindgen will treat it as opaque.
 */
typedef struct LipiTypingContext LipiTypingContext;

/**
 * Owned UTF-8 string allocated by Rust.
 *
 * - `ptr` points to a heap allocation of **len + 1** bytes.
 * - The final byte is always `\\0` for convenience.
 * - The content may be treated as a byte slice of length `len`.
 * - Call `lipi_string_free` to free.
 */
typedef struct LipiString {
  char *ptr;
  size_t len;
  size_t cap;
} LipiString;

/**
 * Options for configuring a typing context.
 */
typedef struct LipiTypingContextOptions {
  uint64_t auto_context_clear_time_ms;
  bool use_native_numerals;
  bool include_inherent_vowel;
} LipiTypingContextOptions;

/**
 * Result of processing a single key in a typing context.
 */
typedef struct LipiTypingDiff {
  /**
   * Number of Unicode scalar chars to delete from the end of the current preedit.
   */
  size_t to_delete_chars_count;
  /**
   * UTF-8 text to append to the preedit.
   */
  struct LipiString diff_add_text;
  /**
   * Remaining internal context length (0 means context was cleared).
   */
  size_t context_length;
} LipiTypingDiff;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Frees a `LipiString` previously returned by this library.
 */
void lipi_string_free(struct LipiString s);

/**
 * Writes default typing options to `out_opts`.
 */
enum LipiStatus lipi_typing_default_options(struct LipiTypingContextOptions *out_opts);

/**
 * Creates a new typing context.
 *
 * - `typing_lang_utf8`: script/language name or alias (UTF-8, NUL-terminated)
 * - `opts`: optional; pass NULL to use Rust defaults
 * - `out_ctx`: receives an opaque context pointer on success
 * - `out_err`: receives an error message on failure (must be freed with `lipi_string_free`)
 */
enum LipiStatus lipi_typing_context_new(const char *typing_lang_utf8,
                                        const struct LipiTypingContextOptions *opts,
                                        struct LipiTypingContext **out_ctx,
                                        struct LipiString *out_err);

/**
 * Destroys a typing context created by `lipi_typing_context_new`.
 */
void lipi_typing_context_free(struct LipiTypingContext *ctx);

/**
 * Clears all internal state and contexts.
 */
enum LipiStatus lipi_typing_context_clear(struct LipiTypingContext *ctx);

/**
 * Processes a single key (expects a UTF-8 string; first Unicode scalar is used).
 *
 * On success writes `out_diff` and returns `LipiStatus::Ok`.
 */
enum LipiStatus lipi_typing_context_take_key_input(struct LipiTypingContext *ctx,
                                                   const char *key_utf8,
                                                   struct LipiTypingDiff *out_diff,
                                                   struct LipiString *out_err);

/**
 * Updates whether native numerals should be used for subsequent typing.
 */
enum LipiStatus lipi_typing_context_set_use_native_numerals(struct LipiTypingContext *ctx,
                                                            bool use_native_numerals);

/**
 * Updates whether inherent vowels should be included for subsequent typing.
 */
enum LipiStatus lipi_typing_context_set_include_inherent_vowel(struct LipiTypingContext *ctx,
                                                               bool include_inherent_vowel);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LIPILEKHIKA_TYPING_H */
