import { script_list_obj } from '../../utils/lang_list';
import type { InputOtherScriptType } from '../input_script_data_schema';

const Normal: InputOtherScriptType = {
  script_name: 'Normal',
  script_id: script_list_obj['Normal'],
  script_type: 'other',
  schwa_character: 'a',
  manual_krama_text_map: {
    ॐ: 'AUM',
    अ: 'a',
    '': 'a',
    ॳ: 'a',
    'ऺ': 'a',
    आ: 'A',
    'ा': 'A',
    ॴ: 'A',
    'ऻ': 'A',
    इ: 'i',
    'ि': 'i',
    ई: 'I',
    'ी': 'I',
    उ: 'u',
    'ु': 'u',
    ॶ: 'u',
    'ॖ': 'u',
    ऊ: 'U',
    'ू': 'U',
    ॷ: 'U',
    'ॗ': 'U',
    ए: 'E',
    'े': 'E',
    ऎ: 'e',
    'ॆ': 'e',
    ऐ: 'ai',
    'ै': 'ai',
    ऍ: 'ai',
    'ॅ': 'ai',
    ओ: 'O',
    'ो': 'O',
    ऒ: 'o',
    'ॊ': 'o',
    औ: 'au',
    'ौ': 'au',
    ऑ: 'au',
    'ॉ': 'au',
    ऋ: 'R',
    'ृ': 'R',
    ॠ: 'RR',
    'ॄ': 'RR',
    ऌ: 'LR',
    'ॢ': 'LR',
    ॡ: 'LRR',
    'ॣ': 'LRR',
    'ं': 'M',
    'ँ': 'MM',
    'ः': 'H',
    ऽ: "''",
    '्': '',
    '़': '',
    '॰': '',
    क: 'k',
    क़: 'kz',
    ख: 'kh',
    ख़: 'khz',
    ग: 'g',
    ग़: 'gz',
    ॻ: 'g',
    घ: 'gh',
    ङ: 'G',
    च: 'C',
    छ: 'Ch',
    ज: 'j',
    ज़: 'jz',
    ॼ: 'j',
    झ: 'jh',
    ञ: 'J',
    त: 't',
    थ: 'th',
    द: 'd',
    ध: 'dh',
    न: 'n',
    ऩ: 'nz',
    ट: 'T',
    ठ: 'Th',
    ड: 'D',
    ड़: 'Dz',
    ॾ: 'D',
    ढ: 'Dh',
    ढ़: 'Dhz',
    ण: 'N',
    प: 'p',
    फ: 'ph',
    फ़: 'phz',
    ब: 'b',
    ॿ: 'b',
    भ: 'bh',
    म: 'm',
    य: 'y',
    य़: 'y',
    व: 'v',
    र: 'r',
    ऱ: 'rz',
    ल: 'l',
    ळ: 'L',
    ऴ: 'Lz',
    ह: 'h',
    स: 's',
    श: 'sh',
    ष: 'Sh',
    // 4 vedic accent symbols
    anudAttA: '↓',
    'udAtta-1': '↑',
    'udAtta-2': '↑↑',
    'udAtta-3': '↑↑↑',
    '०': '0',
    '१': '1',
    '२': '2',
    '३': '3',
    '४': '4',
    '५': '5',
    '६': '6',
    '७': '7',
    '८': '8',
    '९': '9',
    '।': '.',
    '॥': '..'
  },
  list: [
    {
      text: 'C',
      text_krama: ['C'],
      duplicates: ['ch']
    },
    {
      text: 'Ch',
      text_krama: ['Ch'],
      duplicates: ['chh']
    }
  ]
};

export default Normal;
