#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

PREFIX="${PREFIX:-$HOME/.local}"
BUILD_DIR="${BUILD_DIR:-$SCRIPT_DIR/build}"
BUILD_TYPE="${BUILD_TYPE:-Release}"

echo "==> Building Fcitx5 Lipilekhika addon"
echo "    prefix:     ${PREFIX}"
echo "    build dir:  ${BUILD_DIR}"
echo "    build type: ${BUILD_TYPE}"

cmake -S "${SCRIPT_DIR}" -B "${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
  -DCMAKE_INSTALL_PREFIX="${PREFIX}"

cmake --build "${BUILD_DIR}" -j
cmake --install "${BUILD_DIR}"

USER_ADDON_DIR="${PREFIX}/lib/fcitx5"
SYSTEM_ADDON_DIR="/usr/lib/fcitx5"

# Fcitx5 does not automatically search ${PREFIX}/lib/fcitx5 for addon libraries.
# Tell it where to find our locally-installed addon .so.
mkdir -p "$HOME/.config/environment.d"
cat >"$HOME/.config/environment.d/99-fcitx5-lipilekhika.conf" <<EOF
# Auto-generated by lipilekhika/plugins/fcitx5/build.sh
FCITX_ADDON_DIRS=${USER_ADDON_DIR}:${SYSTEM_ADDON_DIR}
EOF

cat <<EOF

==> Installed locally.

Next steps:
  - Restart fcitx5:    fcitx5 -rd
  - Add input method:  "Lipilekhika (Devanagari)" in Fcitx5 config UI

Important:
  - Fcitx5 needs to know where addon libraries live.
  - I wrote: ~/.config/environment.d/99-fcitx5-lipilekhika.conf
    with: FCITX_ADDON_DIRS=${USER_ADDON_DIR}:${SYSTEM_ADDON_DIR}
  - You may need to log out/in (or restart your session) for it to apply everywhere.

To debug addon loading/logs (run in a terminal):
  FCITX_ADDON_DIRS=${USER_ADDON_DIR}:${SYSTEM_ADDON_DIR} fcitx5 -r -D --verbose "*=4,key_trace=5"

EOF

